spring:
  application:
    name: SIMULENEM-backend
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:h2:mem:simulenem
    username: sa
    password: password
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    context-path: /api/v1/

cloud:
  aws:
    s3:
      endpointUrl: http://localhost:4566
      bucketName: my-image-bucket
    credentials:
      accessKey: test
      secretKey: test
    region:
      static: us-east-1
    stack:
      auto: false

